name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar testes com Cypress
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npx cypress run

      # Upload de screenshots (evidências visuais)
      - name: Upload de screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Upload de vídeos (execuções gravadas)
      - name: Upload de vídeos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
