name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Cypress run via action oficial
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npx cypress run
